services:
  # docker-compose up -d mysql_service
  mysql_service:
    image: mysql:8.4
    command: --mysql-native-password=ON
    container_name: mysql_container
    hostname: mysql_host
    ports:
      - "3306:3306"
    privileged: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass # 如果是数字, 则必须加 ""
      MYSQL_NATIVE_PASSWORD: ON
      TZ: Asia/Shanghai
  # docker-compose down mysql_service -v

  # docker-compose up -d redis_service
  redis_service:
    image: redis:latest
    container_name: redis_container
    hostname: redis_host
    ports:
      - "6379:6379"
    restart: always
  # docker-compose down redis_service -v
